### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Jakefeuer** [fcpwiz/support#2]
https://gist.github.com/anonymous/d0e1b3971effcbd4c1eb

**Comment by fcpwiz** [comment]
hmm. try deleting the pack and reinstalling

**Comment by Jakefeuer** [comment]
ok

**Comment by Jakefeuer** [comment]
i just redownloaded it

**Comment by Jakefeuer** [comment]
It crashed again

**Comment by fcpwiz** [comment]
huh i really don't know. ill have to see it in person. sorry

**Comment by Jakefeuer** [comment]
Thats ok
